# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b912150d141403024bb499619c2c0791a42cb3ee79e0be990572dad39aed7bd059ceb78297ab6a269c85130d704f34991af08667b937446844a241c05257f19

test:
  secret_key_base: a823b531980f684069d86ba6970b7fc217b069d173a435fbb5724178c3229a8e9e55729c6352a3acc85a92a31727a101626ad72b00698d4ca9e4b2363666e210

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
